name: get_games
description: A new Flutter project.

publish_to: 'none'  


version: 2.2.0+7

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8
  cached_network_image: ^3.2.3
  url_launcher: ^6.2.1
  http: ^1.1.0
  google_fonts: ^6.1.0
  flex_color_scheme: ^7.3.1
  flutter_local_notifications: ^15.1.1
  flutter_riverpod: ^2.4.0
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  flutter_screenutil: ^5.8.1
  loading_animation_widget: ^1.2.0+4
  easy_localization: ^3.0.3
  dash_flags: ^0.1.1
  flutter_native_splash: ^2.3.5
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  

 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app-icon.png"
  min_sdk_android: 21
 
flutter:

 
  uses-material-design: true

   
  assets:
    - assets/translations/
    - assets/icons/
    
 